# Generated by Django 4.2.7 on 2024-02-15 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0012_alter_brand_image_name_alter_product_image_name_and_more'),
        ('account', '0004_alter_customer_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درج سفارش')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش سفارش')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='نهایی شده/نهایی نشده')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد تولید برای سفارش')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف روی فاکتور')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد کالا')),
                ('price', models.IntegerField(verbose_name='قیمت کالا در فاکتور')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details1', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details2', to='product.product', verbose_name='کالا')),
            ],
        ),
    ]
