# Generated by Django 4.2.7 on 2024-02-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymenttype_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='descrition',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
