# Generated by Django 4.2.7 on 2024-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='کد پیگیری سفارش'),
        ),
    ]
