# Generated by Django 4.2.7 on 2023-12-21 23:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=100, verbose_name='برند')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='نام کالا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='نام تصویر')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت کالا')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='برند کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه کالا')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر گروه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گروه کالا')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('group_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='product.productgroup', verbose_name='والد گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='نام کالا')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار ویژگی')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(through='product.ProductFeature', to='product.feature', verbose_name='ویژگی کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='product.productgroup', verbose_name='گروه های کالا'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product_group',
            field=models.ManyToManyField(related_name='features_of_groups', to='product.productgroup', verbose_name='گروه کالا'),
        ),
    ]
