# Generated by Django 4.2.7 on 2024-01-30 01:13

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productfeature_type_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='type_feature',
            field=models.CharField(default='null', max_length=50, null=True, verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر گروه'),
        ),
    ]
