# Generated by Django 4.2.7 on 2024-02-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_brand_image_name_alter_product_image_name_and_more'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountbasketdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_basket_details2', to='product.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='discountbasketdetails',
            name='discount_basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_basket_details1', to='discount.discountbasket', verbose_name='سبد خرید'),
        ),
    ]
