# Generated by Django 4.2.7 on 2024-02-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discountbasketdetails_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountbasket',
            old_name='end_date',
            new_name='end_date1',
        ),
        migrations.RenameField(
            model_name='discountbasket',
            old_name='start_date',
            new_name='start_date1',
        ),
    ]
