# Generated by Django 4.2.7 on 2024-02-15 05:31

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر پروفایل'),
        ),
    ]
