# Generated by Django 4.2.7 on 2024-03-08 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0024_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type_title', models.CharField(max_length=50, verbose_name='نوع انبار')),
            ],
            options={
                'verbose_name': 'نوع انبار',
                'verbose_name_plural': 'انواع انبار',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='تعداد کالا')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='product.product', verbose_name='کالا')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseuser_registered', to=settings.AUTH_USER_MODEL, verbose_name='کاربر انبار دار')),
                ('warehouse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehousetype', verbose_name='نوع انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
    ]
